### ISSUE TITLE
 Issue with Creation Sidebar: “Could not establish connection” Error

### ISSUE THREAD

**Issue by patrick-michelberger** [marconline/gpsr-sc-chrome#1]
Hi @marconline,

First of all, thank you for this amazing extension and your insightful Medium article—it’s been incredibly helpful!

I’ve cloned the repository and successfully loaded the extension into Chrome. However, when I attempt to use the extension and open the manufacturer creation sidebar, I encounter the following error:

`Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.`

I’ve tried reloading both Seller Central and the extension, but the issue persists. Am I missing a step in the setup process or configuration?

I’ve attached some screenshots of the issue to help illustrate the problem. Let me know if there’s anything else I can provide to assist in debugging.

Thank you in advance for your time and support!

BR
Patrick

**Comment by patrick-michelberger** [comment]
<img width="923" alt="Bildschirmfoto 2024-11-22 um 22 59 48" src="https://github.com/user-attachments/assets/95f43f97-8192-4b42-8822-5d31d8faba37">

<img width="1026" alt="Bildschirmfoto 2024-11-22 um 22 59 26" src="https://github.com/user-attachments/assets/7a819481-010e-43df-87e9-43a48d55dfc7">

**Comment by marconline** [comment]
Thanks @patrick-michelberger . Really appreciated!
